export const CART_FETCH_SUCCESS = 'CART_FETCH_SUCCESS';
export const CART_FETCH_INIT = 'CART_FETCH_INIT';
export const CART_FETCH_ERROR = 'CART_FETCH_ERROR';
export const CLEAR_ALL = 'CLEAR_ALL';
export const DECREASE_ITEM = 'DECREASE_ITEM';
export const INCREASE_ITEM = 'INCREASE_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
